# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perf_date', models.DateTimeField(verbose_name='Date performed')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('entry_date', models.DateTimeField(verbose_name='Date entered')),
            ],
        ),
        migrations.AddField(
            model_name='performance',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminders.Task'),
        ),
    ]
