# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='countdown',
            field=models.BooleanField(default=True, help_text='Countdown or countup?', verbose_name='Countdown'),
        ),
    ]
