# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0006_task_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='colour',
            field=models.CharField(choices=[('#F44336', 'red'), ('#4CAF50', 'green'), ('#FFEB3B', 'yellow'), ('#2196F3', 'blue')], default='#F44336', max_length=7, verbose_name='Colour'),
        ),
    ]
